development:
  adapter: postgresql
  database: neighbormarket_development
  host: localhost
  username: neighbormarket
  password: neighbormarket
  pool: 5
  encoding: unicode

test:
  adapter: postgresql
  database: neighbormarket_test
  host: localhost
  username: neighbormarket
  password: neighbormarket
  pool: 5
  encoding: unicode