production:
    host: 'demo.neighbormarket.org'
    default_from: 'admin@steelheaddigital.com'
    manager_email: 'tmooney3979@gmail.com'
    smtp_settings:
        address: "mail.steelheaddigital.com"
        port: 25
        domain: ''
        user_name: ''
        password: ''
        authentication: 'plain'
        enable_starttls_auto: true
        openssl_verify_mode: 'none' 
development:
    host: 'neighbormarket'
    default_from: ''
    manager_email: ''
    smtp_settings:
        address: ""
        port: 25
        domain: ''
        user_name: ''
        password: ''
        authentication: 'plain'
        enable_starttls_auto: true
        openssl_verify_mode: 'none'
test:
    host: 'test.neighbormarket.org'
    default_from: 'admin@steelheaddigital.com'
