production:
    host: ''
    default_from: ''
    manager_email: ''
    smtp_settings:
        address: ""
        port: 587
        domain: ''
        user_name: ''
        password: ''
        authentication: 'plain'
        enable_starttls_auto: true
development:
    host: ''
    default_from: ''
    manager_email: ''
    smtp_settings:
        address: ""
        port: 587
        domain: ''
        user_name: ''
        password: ''
        authentication: 'plain'
        enable_starttls_auto: true
test:
    host: ''
    default_from: ''
