production:
    host: 'madison.neighbormarket.org'
    default_from: 'madisonnmp@gmail.com'
    smtp_settings:
        address: "smtp.gmail.com"
        port: 587
        domain: 'gmail.com'
        user_name: 'madisonnmp@gmail.com'
        password: '+-n6VZfHf_'
        authentication: 'plain'
        enable_starttls_auto: true
development:
    host: 'localhost:5000'
    default_from: ''
    smtp_settings:
        address: "smtp.gmail.com"
        port: 587
        domain: 'gmail.com'
        user_name: ''
        password: ''
        authentication: 'plain'
        enable_starttls_auto: true
test:
    host: 'test.neighbormarket.org'
    default_from: ''
