production:
    host: 'demo.neighbormarket.org'
    default_from: 'admin@steelheaddigital.com'
    manager_email: 'tmooney3979@gmail.com'
    smtp_settings:
        address: "mail.steelheaddigital.com"
        port: 25
        domain: 'steelheaddigital.com'
        user_name: 'admin@steelheaddigital.com'
        password: 'Portlandrock!'
        authentication: 'plain'
        enable_starttls_auto: true
        openssl_verify_mode: 'none' 
development:
    host: 'neighbormarket'
    default_from: 'admin@steelheaddigital.com'
    manager_email: 'tmooney3979@gmail.com'
    smtp_settings:
        address: "mail.steelheaddigital.com"
        port: 25
        domain: 'steelheaddigital.com'
        user_name: 'admin@steelheaddigital.com'
        password: 'Portlandrock!'
        authentication: 'plain'
        enable_starttls_auto: true
        openssl_verify_mode: 'none'
test:
    host: 'test.neighbormarket.org'
    default_from: 'admin@steelheaddigital.com'
